import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import SideNav from "./components/sideNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen grid`} style={{ gridTemplateRows: 'auto 1fr', gridTemplateColumns: '16rem 1fr' }}>
        <header className="fixed top-0 left-64 right-0 h-16 z-50 bg-white">
          <Header />
        </header>
        <aside className="row-start-2 col-start-1 pt-16">
          <SideNav />
        </aside>
        <main className="row-start-2 col-start-2 pt-14 overflow-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
