import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import SideNav from "./components/sideNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AMOP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen grid`}>
        <div className="fixed top-0 left-0 right-0 z-50 bg-white">
          <Header />
        </div>
        <div className="flex mt-[70px]">
          <div className="w-[20%]">
            <SideNav />

          </div>
          <div className="children-components overflow-auto">
            {children}
          </div>
        </div>

      </body>
    </html>
  );
}
